'$INCLUDE:'menutop.bi'

CONST FALSE = 0, TRUE = NOT FALSE
DIM Menu%
DIM Menushowing%
SCREEN _NEWIMAGE(640, 480, 32)
CLS , _RGB32(50, 100, 200)
_SCREENMOVE _MIDDLE
_MOUSESHOW
MAKEMENU
DO
    WHILE _MOUSEINPUT: WEND
    IF (_MOUSEY < 2) AND (GETMENUSHOWING% = FALSE) THEN SHOWMENU
    IF (_MOUSEY > GETMENUHEIGHT%) AND (GETMENUACTIVE% = FALSE) AND (GETMENUSHOWING% = TRUE) THEN HIDEMENU
    Menu% = CHECKMENU%(TRUE)
LOOP UNTIL Menu% = 103
HIDEMENU
DATA "&File","&Open...#CTRL+O","&Save#CTRL+S","-E&xit#CTRL+Q","*"
DATA "&Help","&About...","*"
DATA "!"

'$INCLUDE:'menu.bi'
