
'$include:'/../../fzxNGN/typesAndConstants/fzxNGNTypes.bas'
$IF SHAREDINCLUDE = UNDEFINED THEN
    $LET SHAREDINCLUDE = TRUE

    DIM SHARED sRESTING AS _FLOAT
    DIM SHARED sNUMBEROFBODIES AS INTEGER: sNUMBEROFBODIES = 10 ' 0 is included
    DIM SHARED sNUMBEROFJOINTS AS INTEGER: sNUMBEROFJOINTS = 3 ' if zero then no joints at all
    DIM SHARED sNUMBEROFVEHICLES AS INTEGER: sNUMBEROFVEHICLES = 1
    DIM SHARED sTIMER AS LONG: sTIMER = TIMER

    DIM SHARED fps AS INTEGER
    DIM SHARED fpsLast AS INTEGER
    DIM SHARED world AS tWORLD
    DIM SHARED objectManager AS tOBJECTMANAGER
$END IF
