$IF CONSTINCLUDE = UNDEFINED THEN
    $LET CONSTINCLUDE = TRUE

    CONST cSHAPE_CIRCLE = 1
    CONST cSHAPE_POLYGON = 2
    CONST cPRECISION = 100

    CONST cMAXNUMOFTRIANGLES = 100
    CONST cMAXNUMBEROFOBJECTS = 1000 ' Max number of objects at one time
    CONST cMAXNUMBEROFPOLYGONS = 10000 ' Max number of total vertices included in all objects
    CONST cMAXNUMBEROFJOINTS = 100
    CONST cMAXNUMBEROFHITS = 10000

    CONST cPI = 3.14159
    CONST cEPSILON = 0.0001
    CONST cEPSILON_SQ = cEPSILON * cEPSILON
    CONST cBIAS_RELATIVE = 0.95
    CONST cBIAS_ABSOLUTE = 0.01
    CONST cDT = 1.0 / 120.0
    CONST cITERATIONS = 100
    CONST cPENETRATION_ALLOWANCE = 0.05
    CONST cPENETRATION_CORRECTION = 0.4 ' misspelled in original code
    CONST cGLOBAL_FRICTION = .992

    CONST cPARAMETER_POSITION = 1
    CONST cPARAMETER_VELOCITY = 2
    CONST cPARAMETER_FORCE = 3
    CONST cPARAMETER_ANGULARVELOCITY = 4
    CONST cPARAMETER_TORQUE = 5
    CONST cPARAMETER_ORIENT = 6
    CONST cPARAMETER_STATICFRICTION = 7
    CONST cPARAMETER_DYNAMICFRICTION = 8
    CONST cPARAMETER_RESTITUTION = 9
    CONST cPARAMETER_COLOR = 10
    CONST cPARAMETER_ENABLE = 11
    CONST cPARAMETER_STATIC = 12
    CONST cPARAMETER_TEXTURE = 13
    CONST cPARAMETER_FLIPTEXTURE = 14
    CONST cPARAMETER_COLLISIONMASK = 15

    CONST cRENDER_JOINTS = 0
    CONST cRENDER_COLLISIONS = 0
    CONST cPLAYER_FORCE = 600000

    CONST cNET_NONE = 0
    CONST cNET_SERVER = 1
    CONST cNET_CLIENT = 2

    CONST cKEY_ESC = 27
    CONST cKEY_TAB = 9
    CONST cKEY_ARROW_UP = 18432
    CONST cKEY_ARROW_DOWN = 20480
    CONST cKEY_ARROW_LEFT = 19200
    CONST cKEY_ARROW_RIGHT = 19712
    CONST cKEY_SPACE = 32

$END IF

